name: task_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  bot_toast: ^4.1.3
  svg_flutter: ^0.0.1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  uuid: ^4.4.2
  get_it: ^7.7.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/

